# Practical 2 - NumPy
### Prepared by: <a href="https://www.linkedin.com/in/a-kanaan/">Dr Abdulkarim M. Jamal Kanaan</a> 
<hr>

## Introduction to NumPy for Machine Learning

In this practical session, we will explore the NumPy package, a fundamental library for scientific computing in Python, with a focus on its applications in machine learning. NumPy provides powerful tools for creating and manipulating multi-dimensional arrays, performing mathematical operations efficiently, and preparing data for machine learning algorithms. Through hands-on exercises and examples, you will learn the essential functionalities of NumPy and gain the necessary skills to leverage its capabilities in your data mining projects.

## Installing NumPy and setting up the environment:

NumPy can be installed using pip, a package installer for Python. Use the following command to install NumPy: `pip install numpy`

## Introduction to NumPy
- Creating 1D and 2D arrays using np.array function.
- Accessing elements in an array using indexing.
- Displaying array attributes such as shape, number of dimensions, and data type.

In [34]:
import numpy as np

# Arrays and Data Structures
print("\nArrays and Data Structures:")
# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)

# Accessing elements in an array
print("\nAccessing elements in an array:")
print("First element of arr1d:", arr1d[0])
print("Element at row 1, column 2 of arr2d:", arr2d[1, 2])

# Array attributes
print("\nArray attributes:")
print("Shape of arr2d:", arr2d.shape)
print("Number of dimensions in arr2d:", arr2d.ndim)
print("Data type of arr2d elements:", arr2d.dtype)


Arrays and Data Structures:
1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Accessing elements in an array:
First element of arr1d: 1
Element at row 1, column 2 of arr2d: 6

Array attributes:
Shape of arr2d: (2, 3)
Number of dimensions in arr2d: 2
Data type of arr2d elements: int32


## Creating, Indexing, Slicing, and Manipulating NumPy Arrays
- Creating NumPy arrays using different methods (e.g., np.array, np.zeros, np.ones).
- Array indexing and slicing.
- Manipulating array shapes and dimensions.

In [35]:
import numpy as np

# Creating NumPy arrays using different methods
arr1 = np.array([1, 2, 3, 4, 5])  # Create a 1D array using np.array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array using np.array
arr3 = np.zeros((3, 4))  # Create a 2D array filled with zeros using np.zeros
arr4 = np.ones((2, 3))  # Create a 2D array filled with ones using np.ones
arr5 = np.arange(1, 10) # Create an array with a specified range of values

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Array 3:\n", arr3)
print("Array 4:\n", arr4)
print("Array 5:\n", arr5)

Array 1:
 [1 2 3 4 5]
Array 2:
 [[1 2 3]
 [4 5 6]]
Array 3:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 4:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array 5:
 [1 2 3 4 5 6 7 8 9]


In [36]:
print("Array 2:\n\n", arr2)
print()
# Array indexing and slicing
print("Array indexing and slicing:")
print("Element at index 1, column 1:", arr2[1, 1])
print("First row:", arr2[0])
print("Elements in the last column:", arr2[:, -1])
print("Slice:", arr2[:, 1:])  # Slicing the second column onwards

# Manipulating array shapes and dimensions
print("\nManipulating array shapes and dimensions:")
reshaped_arr = arr2.reshape((3, 2))  # Reshape the array
print("\nReshaped array:\n", reshaped_arr)

flattened_arr = arr2.flatten()  # Flatten the array
print("\nFlattened array:", flattened_arr)

# Transpose the array
transposed_arr = arr2.T
print("\nTransposed Array:\n", transposed_arr)

Array 2:

 [[1 2 3]
 [4 5 6]]

Array indexing and slicing:
Element at index 1, column 1: 5
First row: [1 2 3]
Elements in the last column: [3 6]
Slice: [[2 3]
 [5 6]]

Manipulating array shapes and dimensions:

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]

Flattened array: [1 2 3 4 5 6]

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


## Mathematical Operations in NumPy

In [37]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Basic arithmetic operations
addition = np.add(arr1, arr2)
subtraction = np.subtract(arr1, arr2)
multiplication = np.multiply(arr1, arr2)
division = np.divide(arr1, arr2)
dot_product = np.dot(arr1, arr2)

# Other mathematical operations
exponential = np.exp(arr1)
square_root = np.sqrt(arr2)
mean_value = np.mean(arr1)
max_value = np.max(arr2)
min_value = np.min(arr1)

# Print the results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Exponential:", exponential)
print("Square Root:", square_root)
print("Mean Value:", mean_value)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)
print("Dot Product:", dot_product)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Square Root: [2.44948974 2.64575131 2.82842712 3.         3.16227766]
Mean Value: 3.0
Maximum Value: 10
Minimum Value: 1
Dot Product: 130


This code demonstrates various mathematical operations that can be performed on NumPy arrays. It showcases basic arithmetic operations like addition, subtraction, multiplication, and division. Additionally, it demonstrates other mathematical operations like exponential calculation, square root, mean value, maximum value, and minimum value.

## Generating Random Numbers and Arrays with NumPy

In [38]:
import numpy as np

# Generating random numbers
print("Generating random numbers:")
rand_num = np.random.rand()  # Generate a random number between 0 and 1
print("Random number:", rand_num)

# Generating random arrays
print("\nGenerating random arrays:")
rand_arr = np.random.rand(3)  # Generate a 1D array of random numbers between 0 and 1
print("1D random array:")
print(rand_arr)

rand_2d_arr = np.random.rand(2, 3)  # Generate a 2D array of random numbers between 0 and 1
print("\n2D random array:")
print(rand_2d_arr)

rand_int_arr = np.random.randint(1, 10, size=5)  # Generate a 1D array of random integers between 1 and 10
print("\n1D random integer array:")
print(rand_int_arr)

# Generating random numbers from a normal distribution
print("\nGenerating random numbers from a normal distribution:")
rand_normal = np.random.normal(loc=0, scale=1, size=5)  # Generate 5 random numbers from a normal distribution
print(rand_normal)

Generating random numbers:
Random number: 0.5628538432150798

Generating random arrays:
1D random array:
[0.58184747 0.306164   0.55682621]

2D random array:
[[0.66305628 0.42510035 0.52069161]
 [0.3949088  0.24368101 0.76282041]]

1D random integer array:
[9 3 3 9 8]

Generating random numbers from a normal distribution:
[ 0.83219982  0.70506567 -0.29140482  0.69299882  0.57206737]


## Advanced Operations
- Boolean array operations and masking.
- Sorting, searching, and indexing.

In [39]:
import numpy as np

# Create arries a, b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Boolean array operations and masking
data = np.array([10, 20, 30, 40, 50])
mask = data > 30
filtered_data = data[mask]

# Sorting, searching, and indexing
arr = np.array([3, 2, 1, 5, 4])
sorted_arr = np.sort(arr)
max_value = np.max(arr)
min_index = np.argmin(arr)

# Print the results
print("\nBoolean array operations and masking:")
print(filtered_data)

print("\nSorting, searching, and indexing:", sorted_arr)
print("Max value:", max_value)
print("Min index:", min_index)


Boolean array operations and masking:
[40 50]

Sorting, searching, and indexing: [1 2 3 4 5]
Max value: 5
Min index: 2


In this example:


- Boolean array operations and masking: We create an array data and apply a boolean condition `(data > 30)` to create a boolean mask. We then use this mask to filter the array and retrieve only the elements that satisfy the condition.

- Sorting, searching, and indexing: We create an array arr and use `np.sort()` to sort the elements in ascending order. We also use `np.max()` to find the maximum value in the array and `np.argmin()` to find the index of the minimum value.